
const MESSAGE_TYPE = {
	TEXT: "TEXT",
	IMAGE: "IMAGE",
	FILE: "FILE",
	RED_PACKETS: "RED_PACKETS",
	TRANSFER: "TRANSFER",
}

const USER_STATE = {
	OFFLINE: 0,
	FREE: 1,
	BUSY: 2
}

const TERMINAL_TYPE = {
	WEB: 0,
	APP: 1
}

const MESSAGE_STATUS = {
	UNSEND: "UNSEND",
	SENDED: "SENDED",
	RECALL: "RECALL",
	READED: "READED"
}

const CMD_TYPE = {
	LOGIN: "LOGIN",
	HEART_BEAT: "HEART_BEAT",
	FORCE_LOGOUT: "FORCE_LOGOUT",
	PRIVATE_MESSAGE: "PRIVATE_MESSAGE",
	GROUP_MESSAGE: "GROUP_MESSAGE",
	SYSTEM_MESSAGE: "SYSTEM_MESSAGE",
	SUBSCRIBE_MESSAGE: "SUBSCRIBE_MESSAGE",
	LOGOUT: "LOGOUT",
}


export {
	MESSAGE_TYPE,
	USER_STATE,
	TERMINAL_TYPE,
	MESSAGE_STATUS,
	CMD_TYPE
}
